name: 'Setup Fortran'
description: Install a Fortran compiler

branding:
  icon: square
  color: yellow

inputs:
  fortran-compiler:
    description: Fortran compiler to install
    required: false
    default: gfortran-latest

runs:
  using: composite
  env:
    INPUT_FORTRAN_COMPILER: ${{ inputs.fortran-compiler }}
  steps:
    - name: Set up Fortran (Linux)
      run: ${{ github.action_path }}/setup_linux.sh
      shell: bash
      if: runner.os == Linux

    - name: Set up Fortran (macOS)
      run: ${{ github.action_path }}/setup_macos.sh
      shell: bash
      if: runner.os == macOS

    - name: Set up Fortran (Windows)
      run: ${{ github.action_path }}/setup_windows.sh
      shell: bash
      if: runner.os == Windows
