name: 'Setup Fortran'
description: Install Fortran compiler

branding:
  icon: square
  color: yellow

inputs:
  fortran-compiler:
    description: Fortran compiler to install
    required: false
    default: gfortran-latest
  enable-cxx:
    description: Install C++ compiler
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Set up Fortran (Linux)
      run: ${{ github.action_path }}/setup-linux.sh
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      env:
        INPUT_FORTRAN_COMPILER: ${{ inputs.fortran-compiler }}
        INPUT_ENABLE_CXX: ${{ inputs.enable-cxx }}

    - name: Set up Fortran (macOS)
      run: ${{ github.action_path }}/setup-macos.sh
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      env:
        INPUT_FORTRAN_COMPILER: ${{ inputs.fortran-compiler }}
        INPUT_ENABLE_CXX: ${{ inputs.enable-cxx }}

    - name: Set up Fortran (Windows)
      run: ${{ github.action_path }}/setup-windows.sh
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      env:
        INPUT_FORTRAN_COMPILER: ${{ inputs.fortran-compiler }}
        INPUT_ENABLE_CXX: ${{ inputs.enable-cxx }}
