#!/bin/bash

. "$GITHUB_ACTION_PATH"/common.sh

OS_VERSION=$(lsb_release -rs)

echo RUNNER_ARCH=$RUNNER_ARCH
echo RUNNER_NAME=$RUNNER_NAME
echo RUNNER_OS=$RUNNER_OS
echo RUNNER_TEMP=$RUNNER_TEMP
echo RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE
echo OS_VERSION=$OS_VERSION
echo INPUT_FORTRAN_COMPILER=$INPUT_FORTRAN_COMPILER
