name: Test

on:
  push:
  pull_request:
  # schedule:
  #   - cron: 0 1 * * 0 # weekly
  # workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-4.8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-5, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-6, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-7, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: default, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-18.04, fortran-compiler: latest, enable-cc: true, enable-cxx: true, enable-gcov: true }

          # - { os: ubuntu-20.04, fortran-compiler: gfortran-7, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: gfortran-8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: default, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-20.04, fortran-compiler: latest, enable-cc: true, enable-cxx: true, enable-gcov: true }

          # - { os: ubuntu-22.04, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-22.04, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-22.04, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-22.04, fortran-compiler: gfortran-12, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-22.04, fortran-compiler: default, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: ubuntu-22.04, fortran-compiler: latest, enable-cc: true, enable-cxx: true, enable-gcov: true }

          # - { os: macos-10.15, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-10.15, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-10.15, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-11, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-11, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-11, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          # - { os: macos-12, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }

          - { os: macos-10.15, fortran-compiler: gfortran-5, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-6, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-7, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-10.15, fortran-compiler: gfortran-12, enable-cc: true, enable-cxx: true, enable-gcov: true }

          - { os: macos-11, fortran-compiler: gfortran-5, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-6, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-7, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-11, fortran-compiler: gfortran-12, enable-cc: true, enable-cxx: true, enable-gcov: true }

          - { os: macos-12, fortran-compiler: gfortran-5, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-6, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-7, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-8, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-9, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-10, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-11, enable-cc: true, enable-cxx: true, enable-gcov: true }
          - { os: macos-12, fortran-compiler: gfortran-12, enable-cc: true, enable-cxx: true, enable-gcov: true }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Fortran
        uses: ./
        with:
          fortran-compiler: ${{ matrix.fortran-compiler }}
          enable-cc: ${{ matrix.enable-cc }}
          enable-cxx: ${{ matrix.enable-cxx }}
          enable-gcov: ${{ matrix.enable-gcov }}

      - name: Check installed executables
        run: |
          echo FC=$FC
          echo CC=$CC
          echo CXX=$CXX
          echo FPM_FC=$FPM_FC
          echo FPM_CC=$FPM_CC
          echo GCOV=$GCOV
          $FC --version
