name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * 0 # weekly
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, fortran-compiler: gfortran-10 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./

      - run: |
          echo FC=$FC
          echo FPM_FC=$FPM_FC
