name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * 0 # weekly
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-18.04, fortran-compiler: gfortran-4.8 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-5 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-6 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-7 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-8 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-9 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-10 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-11 }
          - { os: ubuntu-18.04, fortran-compiler: gfortran-12 }

          - { os: ubuntu-20.04, fortran-compiler: gfortran-4.8 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-5 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-6 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-7 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-8 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-9 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-10 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-11 }
          - { os: ubuntu-20.04, fortran-compiler: gfortran-12 }

          - { os: ubuntu-22.04, fortran-compiler: gfortran-4.8 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-5 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-6 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-7 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-8 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-9 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-10 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-11 }
          - { os: ubuntu-22.04, fortran-compiler: gfortran-12 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          type gfortran-4.8 || :
          type gfortran-5 || :
          type gfortran-6 || :
          type gfortran-7 || :
          type gfortran-8 || :
          type gfortran-9 || :
          type gfortran-10 || :
          type gfortran-11 || :
          type gfortran-12 || :

      - uses: ./
        with:
          fortran-compiler: ${{ matrix.fortran-compiler }}

      - run: |
          echo FC=$FC
          echo FPM_FC=$FPM_FC
